name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (npm ci pour une installation propre)
        run: npm ci

  unit-test:
    runs-on: ubuntu-latest
    needs: pre_install  # Ce job dépend du job "pre_install" pour avoir les dépendances installées
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vitest
        run: npm install -D vitest

      - name: Run tests with Vitest
        run: npm test  # Exécute les tests unitaires avec Vitest

  validate:
    runs-on: ubuntu-latest
    needs: unit-test  # Ce job dépend maintenant de "unit-test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint (npm ci pour une installation propre)
        run: npm ci

      - name: Fix permissions for ESLint
        run: chmod -R +x node_modules/.bin

      - name: Run ESLint (linting)
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: validate  # Ce job dépend maintenant de "validate"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to production
        run: |
          echo "Deploying to production..."

  post_deploy:
    runs-on: ubuntu-latest
    needs: deploy  # Ce job dépend de "deploy"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run post-deploy tasks
        run: |
          echo "Running post-deploy tasks..."
