name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Essayez Node.js 18 pour la compatibilité avec certaines fonctionnalités

      - name: Install dependencies (npm ci pour une installation propre)
        run: npm ci

  build_and_test:
    runs-on: ubuntu-latest
    needs: pre_install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fix permissions for Jest
        run: chmod -R +x node_modules/.bin

      - name: Run tests
        run: npm test

  validate:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint (npm ci pour une installation propre)
        run: npm ci

      - name: Fix permissions for ESLint
        run: chmod -R +x node_modules/.bin

      - name: Run ESLint
        run: npx eslint .  # Exécuter ESLint pour valider le code

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (version 18 recommandée)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to production
        run: |
          echo "Deploying to production..."

  post_deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run post-deploy tasks
        run: |
          echo "Running post-deploy tasks.."
